eureka:
  instance:
    prefer-id-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: PEOPLE-PORTAL
          uri: lb://PEOPLE-PORTAL
          predicates:
            - Path=/people/**
        - id: BANK-PORTAL
          uri: lb://BANK-PORTAL
          predicates:
            - Path=/bank/**, /staff/**



